apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-app
    labels: 
    env: qa 
    project: delivery
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort:  80