apiVersion: v1
kind: ResourceQuota
metadata:
  name: lab-quota
  namespace: dev
spec:
  hard:
    pods: "2"
    # requests.cpu: "2"
    # requests.memory: 2Gi
    # limits.cpu: "4"
    # limits.memory: 4Gi
