apiVersion: apps/v1 #version of the API to use
kind: Deployment #What kind of object we're deploying
metadata: #information about our object we're deploying
  name: nginx-deployment #Name of the deployment
  labels: #A tag on the deployments created
    app: nginxd
spec: #specifications for our object
  strategy:
    type: RollingUpdate
  replicas: 4 #The number of pods that should always be running
  selector: #which pods the replica set should be responsible for
    matchLabels:
      app: nginx #any pods with labels matching this I'm responsible for.
  template: #The pod template that gets deployed
    metadata:
      labels: #A tag on the replica sets created
        app: nginx
    spec:
      containers:
      - name: nginx-container #the name of the container within the pod
        image: nginx:1.14.2 #which container image should be pulled
      # image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80 #the port of the container within the pod

# kubectl apply -f 5.deployment.yml
# kubectl get pods --all

