apiVersion: apps/v1 #version of the API to use
kind: Deployment #What kind of object we're deploying
metadata: #information about our object we're deploying
  name: nginx-deployment #Name of the deployment
  labels: #A tag on the deployments created
    app: nginx
spec: #specifications for our object
  replicas: 2 #The number of pods that should always be running
  selector: #which pods the replica set should be responsible for
    matchLabels:
      app: nginx #any pods with labels matching this I'm responsible for.
  template: #The pod template that gets deployed
    metadata:
      labels: #A tag on the replica sets created
        app: nginx
    spec:
      containers:
        - name: nginx-container #the name of the container within the pod
          image: nginxdemos/hello:plain-text #which container image should be pulled
          ports:
            - containerPort: 80 #the port of the container within the pod
---
apiVersion: v1 #version of the API to use
kind: Service #What kind of object we're deploying
metadata: #information about our object we're deploying
  name: nodeport-nginx #Name of the service
spec: #specifications for our object
  type: NodePort #exposes a service on each nodeâ€™s IP address on a specific port
  ports: #
    - name: http
      port: 80 # service port
      targetPort: 80 #container port
      nodePort: 30001 #port range 30000-32767
      protocol: TCP
  selector: #Label selector used to identify pods
    app: nginx
# kubectl apply -f 6.2nodeport.yaml
# kubectl get nodes -o wide
# curl http://192.168.49.2:30001 execute multiple times observer diffrent pods responding
