apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginxdemos/hello:plain-text
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi


# kubectl apply -f 7.1.emptyDir.yml
# kubectl exec test-pd -it -- /bin/sh 
# pwd
# ls
# ls cache/
# echo test > /cache/textfile 
# ls /cache
# cat /cache/textfile 
# exit


