apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.sname }}"
  namespace: "{{ .Values.service.ns }}"
spec:
  type: ClusterIP #accessble within the cluster
  #type: NodePort #accessble with via all nodes port
  ports: 
  - name: http
    #nodePort: 30001 # used if NodePort enabled- port range 30000-32767
    port: {{ .Values.service.port }} #service port
    targetPort: 80 #container port
    protocol: TCP 
  selector:
    app: nginx
